/**
 * @fileoverview AsyncLocalStorage-backed request ID context for the relayer.
 *
 * Each inbound HTTP request receives a stable request ID (from the
 * X-Request-Id header or a freshly generated UUID). The ID is stored in
 * AsyncLocalStorage so it can be injected into every Pino log line emitted
 * during that request—without any explicit threading of the ID through
 * function arguments.
 *
 * This matches the coordinator's `request-context.ts` so that a request ID
 * generated by the coordinator and forwarded to the relayer (via the
 * X-Request-Id header) is preserved end-to-end, enabling log correlation
 * across both services in a single aggregated sink.
 *
 * Usage
 * -----
 * Register the middleware once during app setup:
 * ```ts
 * import { requestIdMiddleware } from './request-context.js';
 * app.use(requestIdMiddleware);
 * ```
 *
 * Read the active ID anywhere in the call chain:
 * ```ts
 * import { getRequestId } from './request-context.js';
 * const id = getRequestId(); // string | undefined
 * ```
 */

import { AsyncLocalStorage } from 'node:async_hooks';
import { randomUUID } from 'node:crypto';
import type { Request, Response, NextFunction } from 'express';

const _store = new AsyncLocalStorage<string>();

/**
 * Return the request ID bound to the current async context, or `undefined`
 * when called outside an active HTTP request (e.g. background timers, boot).
 */
export function getRequestId(): string | undefined {
  return _store.getStore();
}

/**
 * Express middleware that:
 *  1. Reads `X-Request-Id` from the incoming request headers (if present).
 *  2. Falls back to a freshly generated UUID v4.
 *  3. Runs the rest of the request chain inside an AsyncLocalStorage context
 *     so `getRequestId()` returns the correct ID at any call depth.
 *  4. Echoes the ID back on `X-Request-Id` in the response so clients can
 *     correlate their own logs.
 */
export function requestIdMiddleware(req: Request, res: Response, next: NextFunction): void {
  const incoming = req.headers['x-request-id'];
  const id = typeof incoming === 'string' && incoming.length > 0
    ? incoming
    : randomUUID();

  res.setHeader('X-Request-Id', id);
  _store.run(id, next);
}
